server:
  port: 4070
spring:
  profiles:
    active: dev
    include:
      - datasource
      - email
      - mq
      - redis
      - client
      - seata
  application:
    name: message-service
  cloud:
    nacos:
      server-addr: localhost:8848
      import-check:
        enabled: false
      namespace: ${spring.profiles.active:public}
      discovery:
        ip: localhost
        port: ${server.port}
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
logging:
  level:
    com.message.client: info

---
spring:
  config:
    import:
      - nacos:database.properties?group=message
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:database.properties?group=message
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:database.properties?group=message
    activate:
      on-profile: prod