spring:
  mail:
    host: smtp.163.com
    username: [替换为您的邮箱账号]
    password: [替换为您的邮箱密码]
    port: 465
    properties:
      from: [替换为您的邮箱账号]
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory