spring:
  mail:
    host: smtp.163.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 465
    properties:
      from: ${SMTP_USERNAME}
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory