spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "http://localhost:5173"
            allowed-headers: '*'
            allowed-methods: '*'
            allow-credentials: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: lb://auth-service
          predicates:
            - Path=/api/user/**
        - id: echo
          uri: lb://echo-service
          predicates:
            - Path=/api/echo/**
        - id: message
          uri: lb://message-service
          predicates:
            - Path=/api/message/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/api/pay/**