server:
  port: 4000
spring:
  application:
    name: gateway
  profiles:
    include: route
  cloud:
    nacos:
      server-addr: localhost:8848
      import-check:
        enabled: false
      discovery:
        ip: localhost
        port: ${server.port}
        init-timeout: 30000
        failure-tolerance-enabled: true
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      filter:
        enabled: false
      scg:
        enabled: true
logging:
  level:
    org.springframework.cloud.gateway: INFO