spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: BASIC
            connect-timeout: 5000
            read-timeout: 10000
feign:
  sentinel:
    enabled: true