server:
  port: 4060
spring:
  profiles:
    active: dev
    include:
      - datasource
  application:
    name: echo-service
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

---
spring:
  config:
    import:
      - nacos:database.properties?group=echo
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:database.properties?group=echo
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:database.properties?group=echo
    activate:
      on-profile: prod