server:
  port: 4050
spring:
  profiles:
    active: dev
    include:
      - datasource
      - client
      - seata
      - redis
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: localhost:8848
      import-check:
        enabled: false
      namespace: ${spring.profiles.active:public}
      discovery:
        ip: localhost
        port: ${server.port}
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
logging:
  level:
    com.auth.client: info

---
spring:
  config:
    import:
      - nacos:database.properties?group=auth
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:database.properties?group=auth
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:database.properties?group=auth
    activate:
      on-profile: prod