alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    appId: ${ALIPAY_APP_ID}
    merchantPrivateKey: ${ALIPAY_PRIVATE_KEY}
    alipayPublicKey: ${ALIPAY_PUBLIC_KEY}
    notifyUrl: http://localhost:4000/api/pay/notify