alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    appId: [替换为您的沙箱APPID]
    merchantPrivateKey: [替换为您的应用私钥]
    alipayPublicKey: [替换为支付宝公钥]
    notifyUrl: [替换为您的cpolar穿透地址]/api/pay/notify