spring:
  rabbitmq:
    host: 192.168.157.128
    port: 5672
    virtual-host: /echo
    username: root
    password: 123456
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
    connection-timeout: 1s # 连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数
        max-attempts: 3 # 最大重试次数
        stateless: true # 如果业务中包含事务，这里改为false